# Generated by Django 5.0.4 on 2024-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=20)),
                ("contact_number", models.CharField(max_length=13)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
